Add overloads (multiple signature displayment) support
erhickey/sig-window-nvim pull request #2
Opened 2023-06-29 15:01 UTC by hit9

Before this change:

<img width="1067" alt="image" src="https://github.com/erhickey/sig-window-nvim/assets/1687443/5dd1110d-f9b4-45d0-b3a4-dcbcaec1ac25">

After this change:

<img width="1189" alt="image" src="https://github.com/erhickey/sig-window-nvim/assets/1687443/01f7d62b-37fc-4772-94af-588e6f401f33">

2023-06-29 16:11 UTC, erhickey requested changes
Please update the branch/PR so the commit 16bc5e4 ([Set filetype to floating window's buffer from parent buffer's filetype](https://github.com/erhickey/sig-window-nvim/pull/2/commits/16bc5e4e911bd7f9cf491d360985a097403a88e9)) is not part of it.

2023-06-29 16:11 UTC, erhickey commented on lua/sig-window-nvim.lua
> +  vim.api.nvim_buf_set_lines(w_bufnr, 0, -2, true, other_labels)
Why change the 3rd argument (end) to nvim_buf_set_lines from -1 to -2?

2023-06-29 16:11 UTC, erhickey commented on lua/sig-window-nvim.lua
> +  local lines = other_labels
Is this lines variable necessary?

2023-06-29 16:11 UTC, erhickey commented on lua/sig-window-nvim.lua
>    local winnr = vim.api.nvim_open_win(w_bufnr, false, window_config(label, config, width, height))
I think window_config should be updated to take other_labels (without the active label) as the last argument, but that doesn't need to be done in this PR. I will take that change on and update the documentation.

2023-06-29 16:11 UTC, erhickey commented on lua/sig-window-nvim.lua
> +  text = table.concat(lines, "\n")
I think this is over-simplifying the problem. Each line should be checked to determine the appropriate width and height. I'm ok with fixing this after merging the PR, I think this simple solution is sufficient for now. Feel free to leave this as is or take a stab at it.

2023-06-30 06:20 UTC, hit9 commented on lua/sig-window-nvim.lua
> +  vim.api.nvim_buf_set_lines(w_bufnr, 0, -2, true, other_labels)
oh.. this is my typo changes.

2023-07-03 13:04 UTC, hit9 commented
> Please update the branch/PR so the commit [16bc5e4](https://github.com/erhickey/sig-window-nvim/commit/16bc5e4e911bd7f9cf491d360985a097403a88e9) ([Set filetype to floating window's buffer from parent buffer's filetype](https://github.com/erhickey/sig-window-nvim/pull/2/commits/16bc5e4e911bd7f9cf491d360985a097403a88e9)) is not part of it.

Forced pushed now. this commit was removed.

2023-07-03 17:40 UTC, erhickey approved these changes
looks good, thanks for the updates and the contribution

2023-07-03 17:41 UTC, merged